[project]
name = "monorepo-worker"
version = "0.1.0"
description = "Background worker using Celery"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "monorepo-core",
    "celery>=5.3.0",
    "redis>=5.0.0",
    "kombu>=5.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
]

[tool.uv.sources]
monorepo-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/worker_app"]

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/tests",
]